### ISSUE TITLE
Mirror doesn't start after I added the module

### ISSUE THREAD

**Issue by loosve** [cowboysdude/MMM-DNews#2]
When I add that module in my config I can't start the Mirror.
I get this message:

 `[12:09:30.351] [LOG]    Starting MagicMirror: v2.10.1
[12:09:30.355] [LOG]    Loading config ...
[12:09:30.357] [LOG]    Loading module helpers ...
[12:09:30.357] [LOG]    No helper found for module: MMM-pages.
[12:09:30.358] [LOG]    No helper found for module: clock.
[12:09:30.358] [LOG]    No helper found for module: MMM-OpenmapWeather.
[12:09:30.456] [LOG]    Initializing new module helper ...
[12:09:30.456] [LOG]    Module helper loaded: MMM-3Day-Forecast
[12:09:30.457] [LOG]    Initializing new module helper ...
[12:09:30.457] [LOG]    Module helper loaded: MMM-PNews
[12:09:30.457] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'xml2js'
[12:09:30.458] [LOG]    Loading module helpers ...
[12:09:30.458] [LOG]    No helper found for module: MMM-pages.
[12:09:30.458] [LOG]    No helper found for module: clock.
[12:09:30.458] [LOG]    No helper found for module: MMM-OpenmapWeather.
[12:09:30.458] [LOG]    Initializing new module helper ...
[12:09:30.458] [LOG]    Module helper loaded: MMM-3Day-Forecast
[12:09:30.458] [LOG]    Initializing new module helper ...
[12:09:30.458] [LOG]    Module helper loaded: MMM-PNews
[12:09:30.459] [LOG]    Whoops! There was an uncaught exception...
[12:09:30.459] [ERROR]  { Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/home/admin/MagicMirror-GS/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/admin/MagicMirror-GS/modules/MMM-DNews/node_helper.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }
[12:09:30.461] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[12:09:30.461] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`

I copy and pasted the config entry from the readme file of this module.
When I remove the module from my config file the Mirror starts again. So it seems like that the module has an issue?

This is how the config entry of the module looks like in my config file:
`{
           module: 'MMM-DNews',
				position: 'bottom_bar',
				config: {
					rotateInterval: 20 * 1000 
					}
		},`

**Comment by loosve** [comment]
Okay I solved the problem. I had to run `npm install` in the MagicMirror/modules/MMM-DNews folder.
