### ISSUE TITLE
Error after re-install Mirror

### ISSUE THREAD

**Issue by BlueForrest** [cowboysdude/MMM-DNews#3]
Hi, long time ago you made this module so I could see some local news.
Now I re-installed the mirror after upgraded to an RPI4-4GB  and this module gives me an error.  
Would you mind have a look at this.

I would like to see this feed on my mirror again : 
` http://www.nieuwsblad.be/rss/section/c1e533dc-ff1c-40fc-b48c-77ee686d54d4?intro=1",  `

I installed the PNews but unfortunately it works with an API key (which I have) but my news source isn't available.

Hope you can help.

this is the error:
`
[04.12.2021 10:42.09.832] [ERROR] Whoops! There was an uncaught exception...
[04.12.2021 10:42.09.837] [ERROR] Error: Cannot find module 'xml2js'
Require stack:
- /home/pi/MagicMirror/modules/MMM-DNews/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-DNews/node_helper.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at loadModule (/home/pi/MagicMirror/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at loadModule (/home/pi/MagicMirror/js/app.js:146:4) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-DNews/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[04.12.2021 10:42.09.839] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

`

**Comment by cowboysdude** [comment]
Need to run npm install in Dnews directory now.
